### ISSUE TITLE
random crash

### ISSUE THREAD

**Issue by FRBFStudios** [SpaghettDev/BetterInputs#7]
the crashlog says betterinputs in it so i'm reporting it here, i was leaving a comment but i can't remember what i pressed when it crashed

[2024-07-24_15-49-28.txt](https://github.com/user-attachments/files/16363086/2024-07-24_15-49-28.txt)

**Comment by SpaghettDev** [comment]
yeah you have both BetterInputs and EZClipboard and those two won't like eachother. Remove one of them
